
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'D70A4A7143E430188CF2A604C676E1C7'
    
_lr_action_items = {'TIMES':([20,21,24,25,],[22,-13,-12,22,]),'LBRACE':([5,6,],[8,-5,]),'RBRACE':([8,11,14,17,],[-7,15,-7,-8,]),'SEMI':([4,6,10,15,18,20,21,24,25,],[7,-5,14,-4,-9,-10,-13,-12,-11,]),'PLUS':([20,21,24,25,],[23,-13,-12,-11,]),'LARROW':([6,18,],[-5,19,]),'COLON':([12,13,],[-6,16,]),'INTEGER':([19,22,23,],[21,21,21,]),'IDENTIFIER':([8,14,],[12,12,]),'TYPE':([2,16,],[6,6,]),'CLASS':([0,7,],[2,2,]),'$end':([0,1,3,7,9,],[-2,-1,0,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'classlist':([0,7,],[1,9,]),'feature':([8,14,],[10,10,]),'program':([0,],[3,]),'featurelist':([8,14,],[11,17,]),'exp':([19,22,23,],[20,24,25,]),'identifier':([8,14,],[13,13,]),'type':([2,16,],[5,18,]),'class':([0,7,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> classlist','program',1,'p_program_classlist','main.py',140),
  ('classlist -> <empty>','classlist',0,'p_classlist_none','main.py',144),
  ('classlist -> class SEMI classlist','classlist',3,'p_classlist_some','main.py',148),
  ('class -> CLASS type LBRACE featurelist RBRACE','class',5,'p_class_noinherit','main.py',153),
  ('type -> TYPE','type',1,'p_type','main.py',157),
  ('identifier -> IDENTIFIER','identifier',1,'p_identifier','main.py',161),
  ('featurelist -> <empty>','featurelist',0,'p_featurelist_none','main.py',165),
  ('featurelist -> feature SEMI featurelist','featurelist',3,'p_featurelist_some','main.py',169),
  ('feature -> identifier COLON type','feature',3,'p_feature_attribute_no_init','main.py',176),
  ('feature -> identifier COLON type LARROW exp','feature',5,'p_feature_attribute_init','main.py',180),
  ('exp -> exp PLUS exp','exp',3,'p_exp_plus','main.py',187),
  ('exp -> exp TIMES exp','exp',3,'p_exp_times','main.py',191),
  ('exp -> INTEGER','exp',1,'p_exp_integer','main.py',195),
]
